### ISSUE TITLE
パスワード入力時に、入力を非表示にしたい

### ISSUE THREAD

**Issue by Cj-bc** [rainy-me/dhu#36]
パスワードを打つ際、画面に表示されるのはセキュリティ上あまり良くないので、なんとか隠したいです。
ですが、軽く調べた所nodeのreadlineでは標準でその機能はないようですね...
[npm/read](https://www.npmjs.com/package/read)は求めている機能を持っているようですが、最終更新が6年前なので使えるのか微妙です...(そもそもTypeScriptと上手く動くのかもわかりません)

調べると方法はあるみたいですが、どれが良いのかとかは良く分からないです
https://stackoverflow.com/questions/24037545/how-to-hide-password-in-the-nodejs-console

**Comment by rainy-me** [comment]
@Cj-bc 調査ありがとうございます。こちらも調べてみます。

**Comment by rainy-me** [comment]
stdin/outで遊んで見たけど、https://github.com/vadimdemedes/ink のほうが将来性あると思いました。

**Comment by rainy-me** [comment]
@Cj-bc https://github.com/rainy-me/dhu/releases/tag/0.1.0 にて実装しました。

**Comment by Cj-bc** [comment]
おぉそんなものが...試してみましたが良いですね!
