### ISSUE TITLE
loginに失敗した時の例外をきちんと処理したい

### ISSUE THREAD

**Issue by Cj-bc** [rainy-me/dhu#38]
現状、loginに失敗すると以下のように`UnhandledPromiseRejection`が吐かれます。
![20210501123856](https://user-images.githubusercontent.com/16875061/116972247-b47d2f00-acf5-11eb-9106-fb3e300f60a4.png)

ちょっとエラーとして見辛いので、handleしたいなと思っています。

ちなみに自分でも[Promiseの`then`を使って一部だけ書いてみた](https://github.com/Cj-bc/dhu/commit/a1f06ccbfe56d164a88c3eb85bc175807a4ed00e)のですが、

以下のようにエラーを表示した後固まってしまい、どうすれば良いのか分からない状況です...

https://user-images.githubusercontent.com/16875061/116979559-1d69a480-ad00-11eb-957e-9b2513971118.mp4

**Comment by rainy-me** [comment]
@Cj-bc https://github.com/Cj-bc/dhu/commit/a1f06ccbfe56d164a88c3eb85bc175807a4ed00e は一部fixしていたが、`withLoginedPage` をawaitしていないためprocessが終了してないですね。しかしエラー処理全般あんまりしてないので、（動くまで作って放置した）。もしちゃんとやりたいであれば見直しが必要な箇所はこの一つだけではなく、もっとありますね。

**Comment by Cj-bc** [comment]
元々は`await`つけたままだったのですが、それでも同じように固まったので外してみました。
`await`は必要だとなると、どこかでresolveできていない...?

とりあえず一箇所で上手くエラー処理できたら他の部分も修正してみようと思っていました。

**Comment by rainy-me** [comment]
なるほど、そうだとしたら`withLoginedPage`中の処理の問題になるので、雑ではありますが、一時的に`process.exit()`していいと思いました。

**Comment by Cj-bc** [comment]
あ!!!分かった気がします
https://github.com/rainy-me/dhu/blob/614b4f113151cf4e0ef7ffee015f5dfe6bef2dd1/packages/core/login.ts#L53-L56

ここで、入力にエラーがあった場合には`error`を返しているわけですが、このログインを実行する時に使った`browser`が閉じられていないです。
試しに

``` diff
   if (error) {                                                                                                                                                                     
      await removeUserInfo();
+    await browser.close();
      return { error };
      }
```
としたら直りました

![20210504210258](https://user-images.githubusercontent.com/16875061/117000517-27999c00-ad1c-11eb-8cd5-22b8b972fcf1.png)

**Comment by rainy-me** [comment]
@Cj-bc あとここですね。throwではなくlog & returnにしたほうが良さな気がします。 https://github.com/rainy-me/dhu/blob/e1b386786b08fcc9e069b69ebf7e23f4f16e3525/packages/core/login.ts#L68-L70

**Comment by Cj-bc** [comment]
returnにする場合、Promiseでの失敗を実質握り潰してるように感じるのですがそこは良いのでしょうか...?
HaskellのMonadに近いものを感じていたので、失敗は失敗として扱った方が綺麗かなと思っていました
(返り値で表現することも可能だけど、どうせPromise使うならその機能を使った方が良いのかなと)

**Comment by rainy-me** [comment]
今の問題どちらというとどのレイヤーでerrorを処理するのを決まっていないので、私的にerror messageを綺麗に表示てきたらそれだけでいいと思っていて、実装にこだわってないです...
